Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  # All boxes are based on a CentOS 7 box
  config.vm.box = "centos/7"

  # Ensure that all Vagrant machines will use the same SSH key pair.
  config.ssh.insert_key = false

  # Define our virtual machines
  config.vm.define "cd" do |d|
    d.vm.hostname = "cd"
    d.vm.network :private_network, ip: "10.100.198.10"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end

  config.vm.define "audit-service" do |d|
    d.vm.hostname = "audit-service"
    d.vm.network :private_network, ip: "10.100.198.101"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/simple_playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 256
    end
  end

  config.vm.define "compulsive-traders" do |d|
    d.vm.hostname = "compulsive-traders"
    d.vm.network :private_network, ip: "10.100.198.102"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/simple_playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 256
    end
  end

  config.vm.define "portfolio-service" do |d|
    d.vm.hostname = "portfolio-service"
    d.vm.network :private_network, ip: "10.100.198.103"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/simple_playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 256
    end
  end

  config.vm.define "quote-generator" do |d|
    d.vm.hostname = "quote-generator"
    d.vm.network :private_network, ip: "10.100.198.104"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/simple_playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 256
    end
  end

  config.vm.define "trader-dashboard" do |d|
    d.vm.hostname = "trader-dashboard"
    d.vm.network :private_network, ip: "10.100.198.105"
    d.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "provisioning/simple_playbook.yml"
    end
    d.vm.provider "virtualbox" do |v|
      v.memory = 256
    end
  end
end